spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fittrack
    username: drack
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true